"use client";
import {useCallback,useEffect,useState} from 'react';
import {useParams} from 'next/navigation';
import Link from 'next/link';

type Alias={alias:string;command:string};
type FileItem={name:string;type:'file'|'directory';size:number|null};
type Backup={name:string;size:number;createdAt:string};
type Server={id:string;name:string;slug:string;version:string;type:string;status:string;ramMb:number;port:number;address:string;motd:string;maxPlayers:number;gamemode:string;difficulty:string;hardcore:boolean;pvp:boolean;onlineMode:boolean;whitelist:boolean;commandAliases:Alias[]|null;worlds:any[]};

export default function ServerPage(){
 const {id:raw}=useParams();const id=String(raw);const [s,setS]=useState<Server|null>(null);const [tab,setTab]=useState('overview');const [logs,setLogs]=useState('');const [command,setCommand]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [settings,setSettings]=useState<any>({});const [aliases,setAliases]=useState<Alias[]>([]);const [pluginUrl,setPluginUrl]=useState('');const [plugins,setPlugins]=useState<string[]>([]);const [world,setWorld]=useState<any>({worldName:'world',seed:'',gamemode:'survival',difficulty:'normal',levelType:'minecraft:normal'});const [files,setFiles]=useState<FileItem[]>([]);const [selectedFile,setSelectedFile]=useState('');const [fileContent,setFileContent]=useState('');const [backups,setBackups]=useState<Backup[]>([]);const [newBackup,setNewBackup]=useState('');const [player,setPlayer]=useState('');
 const load=useCallback(async()=>{const r=await fetch('/api/servers/'+id);if(!r.ok)return;const d=await r.json();setS(d);setSettings(d);setAliases(d.commandAliases||[]);const w=d.worlds?.[0];if(w)setWorld({worldName:w.name,seed:w.seed||'',gamemode:w.gamemode,difficulty:w.difficulty,levelType:w.levelType||'minecraft:normal'});},[id]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(tab!=='console'||!s)return;const f=async()=>{const r=await fetch('/api/servers/'+id+'/console');if(r.ok)setLogs((await r.json()).logs||'')};f();const t=setInterval(f,2500);return()=>clearInterval(t)},[tab,id,s]);
 useEffect(()=>{if(tab==='plugins')fetch('/api/servers/'+id+'/plugins').then(r=>r.json()).then(d=>setPlugins(d.plugins||[]));if(tab==='files')fetch('/api/servers/'+id+'/files').then(r=>r.json()).then(d=>setFiles(d.files||[]));if(tab==='backups')fetch('/api/servers/'+id+'/backups').then(r=>r.json()).then(d=>setBackups(d.backups||[]))},[tab,id]);
 async function action(a:string){setBusy(true);const r=await fetch('/api/servers/'+id+'/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:a})});const d=await r.json();setNotice(r.ok?(a==='start'?'Server gestartet.':a==='stop'?'Server gestoppt.':'Server neu gestartet.'):d.error||'Aktion fehlgeschlagen');await load();setBusy(false)}
 async function saveSettings(){setBusy(true);const r=await fetch('/api/servers/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...settings,ramMb:Number(settings.ramMb),maxPlayers:Number(settings.maxPlayers),commandAliases:aliases})});const d=await r.json();setNotice(r.ok?'Einstellungen gespeichert.':d.error||'Speichern fehlgeschlagen');if(r.ok){setS(d);setSettings(d)}setBusy(false)}
 async function sendCommand(){const text=command.trim();if(!text)return;setCommand('');const r=await fetch('/api/servers/'+id+'/console',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:text})});const d=await r.json();setLogs(v=>v+`\n> ${text}\n${d.output||d.error||''}`)}
 async function saveWorld(reset:boolean){setBusy(true);const r=await fetch('/api/servers/'+id+'/world',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...world,reset})});const d=await r.json();setNotice(r.ok?(reset?'Welt zurückgesetzt.':'Welteinstellungen gespeichert.'):d.error||'Weltfehler');await load();setBusy(false)}
 async function installPlugin(){if(!pluginUrl.trim())return;setBusy(true);const r=await fetch('/api/servers/'+id+'/plugins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:pluginUrl.trim()})});const d=await r.json();setNotice(r.ok?`${d.file} installiert.`:d.error||'Plugin konnte nicht installiert werden');setPluginUrl('');if(r.ok){const pr=await fetch('/api/servers/'+id+'/plugins');setPlugins((await pr.json()).plugins||[])}setBusy(false)}
 async function openFile(name:string){setSelectedFile(name);const r=await fetch('/api/servers/'+id+'/files?name='+encodeURIComponent(name));const d=await r.json();setFileContent(r.ok?d.content:(d.error||''))}
 async function saveFile(){const r=await fetch('/api/servers/'+id+'/files',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:selectedFile,content:fileContent})});setNotice(r.ok?'Datei gespeichert.':(await r.json()).error||'Datei konnte nicht gespeichert werden')}
 async function createBackup(){setBusy(true);const r=await fetch('/api/servers/'+id+'/backups',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:newBackup||undefined})});const d=await r.json();setNotice(r.ok?`Backup ${d.name} erstellt.`:d.error||'Backup fehlgeschlagen');setNewBackup('');const b=await fetch('/api/servers/'+id+'/backups');if(b.ok)setBackups((await b.json()).backups||[]);setBusy(false)}
 async function playerCommand(cmd:string){if(!player.trim())return;setCommand(`${cmd} ${player.trim()}`);setTab('console')}
 if(!s)return <main className="wrap"><Link className="btn dark" href="/dashboard">← Zurück</Link><p>Lade Server...</p></main>;
 const nav=[['overview','Übersicht'],['settings','⚙ Einstellungen'],['world','🌍 Welt'],['console','🖥 Konsole'],['plugins','🧩 Plugins'],['commands','⌘ Commands'],['files','📁 Dateien'],['players','👥 Spieler'],['backups','📦 Backups']];
 return <main className="wrap"><div className="nav"><Link className="btn dark" href="/dashboard">← Server</Link><div className="logo">⛏ {s.name}</div><span className="pill">{s.status}</span></div>
  <div className="heroBox"><div className="muted">SERVER-ADRESSE · FREUNDE KÖNNEN DIESE ADRESSE VERWENDEN</div><div style={{fontSize:28,fontWeight:800,marginTop:8}}>{s.address}</div><div className="muted" style={{marginTop:8}}>{s.motd}</div><div className="tabs"><button className="btn" disabled={busy} onClick={()=>action('start')}>▶ Start</button><button className="btn dark" disabled={busy} onClick={()=>action('stop')}>■ Stop</button><button className="btn dark" disabled={busy} onClick={()=>action('restart')}>↻ Restart</button>{notice&&<span className="muted" style={{alignSelf:'center'}}>{notice}</span>}</div></div>
  <div className="tabs">{nav.map(([key,label])=><button key={key} className="tab" style={tab===key?{outline:'2px solid #3ddc84'}:{}} onClick={()=>setTab(key)}>{label}</button>)}</div>
  {tab==='overview'&&<div className="grid"><div className="card"><h3>Software</h3><div className="stat">{s.type}</div><div className="muted">Minecraft {s.version}</div></div><div className="card"><h3>RAM</h3><div className="stat">{s.ramMb/1024} GB</div></div><div className="card"><h3>Spieler</h3><div className="stat">max. {s.maxPlayers}</div></div><div className="card"><h3>Spielmodus</h3><div className="stat" style={{fontSize:22}}>{s.gamemode}</div><div className="muted">Schwierigkeit: {s.difficulty}</div></div><div className="card"><h3>Hardcore</h3><div className="stat" style={{fontSize:22}}>{s.hardcore?'AKTIV':'Aus'}</div></div><div className="card"><h3>Welt</h3><div className="stat" style={{fontSize:22}}>{s.worlds?.[0]?.name||'world'}</div></div></div>}
  {tab==='settings'&&<div className="card"><h2>Server-Einstellungen</h2><div className="grid" style={{gridTemplateColumns:'1fr 1fr'}}><input className="input" value={settings.name||''} onChange={e=>setSettings({...settings,name:e.target.value})} placeholder="Servername"/><input className="input" value={settings.motd||''} onChange={e=>setSettings({...settings,motd:e.target.value})} placeholder="MOTD"/><select className="input" value={settings.type||'PAPER'} onChange={e=>setSettings({...settings,type:e.target.value})}><option value="PAPER">Paper</option><option value="VANILLA">Vanilla</option><option value="SPIGOT">Spigot</option><option value="PURPUR">Purpur</option></select><select className="input" value={settings.version||'1.21.8'} onChange={e=>setSettings({...settings,version:e.target.value})}><option>1.21.8</option><option>1.21.7</option><option>1.21.6</option><option>1.21.5</option><option>1.20.6</option></select><select className="input" value={settings.ramMb||2048} onChange={e=>setSettings({...settings,ramMb:Number(e.target.value)})}><option value={1024}>1 GB</option><option value={2048}>2 GB</option><option value={4096}>4 GB</option><option value={8192}>8 GB</option></select><input className="input" type="number" min={1} max={100} value={settings.maxPlayers||20} onChange={e=>setSettings({...settings,maxPlayers:Number(e.target.value)})}/><select className="input" value={settings.gamemode||'survival'} onChange={e=>setSettings({...settings,gamemode:e.target.value})}><option>survival</option><option>creative</option><option>adventure</option><option>spectator</option></select><select className="input" value={settings.difficulty||'normal'} onChange={e=>setSettings({...settings,difficulty:e.target.value})}><option>peaceful</option><option>easy</option><option>normal</option><option>hard</option></select></div><div className="tabs"><label className="tab"><input type="checkbox" checked={!!settings.hardcore} onChange={e=>setSettings({...settings,hardcore:e.target.checked})}/> Hardcore</label><label className="tab"><input type="checkbox" checked={settings.pvp!==false} onChange={e=>setSettings({...settings,pvp:e.target.checked})}/> PvP</label><label className="tab"><input type="checkbox" checked={settings.onlineMode!==false} onChange={e=>setSettings({...settings,onlineMode:e.target.checked})}/> Online Mode</label><label className="tab"><input type="checkbox" checked={!!settings.whitelist} onChange={e=>setSettings({...settings,whitelist:e.target.checked})}/> Whitelist</label></div><button className="btn" disabled={busy} onClick={saveSettings}>💾 Speichern</button></div>}
  {tab==='world'&&<div className="card"><h2>Weltverwaltung</h2><div className="grid" style={{gridTemplateColumns:'1fr 1fr'}}><input className="input" value={world.worldName} onChange={e=>setWorld({...world,worldName:e.target.value})} placeholder="Weltname"/><input className="input" value={world.seed} onChange={e=>setWorld({...world,seed:e.target.value})} placeholder="Seed (leer = zufällig)"/><select className="input" value={world.gamemode} onChange={e=>setWorld({...world,gamemode:e.target.value})}><option>survival</option><option>creative</option><option>adventure</option></select><select className="input" value={world.difficulty} onChange={e=>setWorld({...world,difficulty:e.target.value})}><option>peaceful</option><option>easy</option><option>normal</option><option>hard</option></select><select className="input" value={world.levelType} onChange={e=>setWorld({...world,levelType:e.target.value})}><option value="minecraft:normal">Normal</option><option value="minecraft:flat">Flat</option><option value="minecraft:amplified">Amplified</option></select></div><div className="tabs"><button className="btn" disabled={busy} onClick={()=>saveWorld(false)}>💾 Welt speichern</button><button className="btn dark" disabled={busy} onClick={()=>saveWorld(true)}>♻ Welt zurücksetzen</button></div></div>}
  {tab==='console'&&<div className="card"><h2>Live-Konsole</h2><pre style={{background:'#050a06',padding:16,borderRadius:12,minHeight:360,maxHeight:520,overflow:'auto',whiteSpace:'pre-wrap'}}>{logs||'Noch keine Logausgabe.'}</pre><div style={{display:'flex',gap:8,marginTop:10}}><input className="input" value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendCommand()} placeholder="z. B. say Hallo oder gamemode creative Spieler"/><button className="btn" onClick={sendCommand}>Senden</button></div></div>}
  {tab==='plugins'&&<div className="card"><h2>Plugins installieren</h2><p className="muted">Servertyp Paper, Spigot oder Purpur wählen und eine direkte JAR-URL verwenden.</p><div style={{display:'flex',gap:8}}><input className="input" value={pluginUrl} onChange={e=>setPluginUrl(e.target.value)} placeholder="https://example.com/plugin.jar"/><button className="btn" disabled={busy||!pluginUrl.trim()} onClick={installPlugin}>⬇ Installieren</button></div><div style={{marginTop:16}}>{plugins.map(x=><div className="server card" key={x}><span>🧩 {x}</span><span className="pill">installiert</span></div>)}{!plugins.length&&<p className="muted">Noch keine Plugins.</p>}</div></div>}
  {tab==='commands'&&<div className="card"><h2>Eigene Commands</h2><p className="muted">Lege einfache Aliase an und speichere sie direkt im Server.</p>{aliases.map((a,i)=><div className="tabs" key={i}><input className="input" value={a.alias} onChange={e=>setAliases(v=>v.map((x,j)=>j===i?{...x,alias:e.target.value}:x))} placeholder="alias"/><input className="input" value={a.command} onChange={e=>setAliases(v=>v.map((x,j)=>j===i?{...x,command:e.target.value}:x))} placeholder="say Hallo"/><button className="btn dark" onClick={()=>setAliases(v=>v.filter((_,j)=>j!==i))}>Löschen</button></div>)}<div className="tabs"><button className="btn dark" onClick={()=>setAliases(v=>[...v,{alias:'meincommand',command:'say Hallo'}])}>+ Hinzufügen</button><button className="btn" disabled={busy} onClick={saveSettings}>💾 Speichern</button></div></div>}
  {tab==='files'&&<div className="card"><h2>Dateimanager</h2><div className="grid" style={{gridTemplateColumns:'260px 1fr'}}><div>{files.map(f=><button key={f.name} className="tab" style={{display:'block',width:'100%',textAlign:'left',marginBottom:6}} onClick={()=>f.type==='file'&&openFile(f.name)}>{f.type==='directory'?'📁':'📄'} {f.name}</button>)}{!files.length&&<p className="muted">Keine Dateien gefunden.</p>}</div><div>{selectedFile?<><div className="tabs"><b>{selectedFile}</b><button className="btn" onClick={saveFile}>💾 Datei speichern</button></div><textarea className="input" style={{minHeight:400,fontFamily:'monospace'}} value={fileContent} onChange={e=>setFileContent(e.target.value)}/></>:<p className="muted">Klicke links eine Textdatei an, um sie zu bearbeiten.</p>}</div></div></div>}
  {tab==='players'&&<div className="card"><h2>Spielerverwaltung</h2><input className="input" value={player} onChange={e=>setPlayer(e.target.value)} placeholder="Spielername"/><div className="tabs"><button className="btn" onClick={()=>playerCommand('op')}>OP</button><button className="btn dark" onClick={()=>playerCommand('deop')}>DEOP</button><button className="btn dark" onClick={()=>playerCommand('whitelist add')}>Whitelist +</button><button className="btn dark" onClick={()=>playerCommand('whitelist remove')}>Whitelist −</button><button className="btn dark" onClick={()=>playerCommand('kick')}>Kick</button></div><p className="muted">Die Aktionen öffnen die Konsole bereits mit dem passenden Befehl, sodass du ihn direkt ausführen kannst.</p></div>}
  {tab==='backups'&&<div className="card"><h2>Backups</h2><div className="tabs"><input className="input" value={newBackup} onChange={e=>setNewBackup(e.target.value)} placeholder="Name optional"/><button className="btn" disabled={busy} onClick={createBackup}>📦 Backup erstellen</button></div>{backups.map(b=><div className="server card" key={b.name}><div><b>{b.name}</b><div className="muted">{new Date(b.createdAt).toLocaleString()} · {Math.round(b.size/1024)} KB</div></div><span className="pill">gesichert</span></div>)}{!backups.length&&<p className="muted">Noch keine Backups.</p>}</div>}
 </main>
}