"use client";
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';

type Alias={alias:string;command:string};
type Server={id:string;name:string;slug:string;version:string;type:string;status:string;ramMb:number;port:number;address:string;motd:string;maxPlayers:number;gamemode:string;difficulty:string;hardcore:boolean;pvp:boolean;onlineMode:boolean;whitelist:boolean;commandAliases:Alias[]|null;worlds:any[]};

export default function ServerPage(){
  const p=useParams(); const id=String(p.id); const [s,setS]=useState<Server|null>(null); const [tab,setTab]=useState('overview'); const [logs,setLogs]=useState(''); const [command,setCommand]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false);
  const [settings,setSettings]=useState<any>({}); const [aliases,setAliases]=useState<Alias[]>([]); const [pluginUrl,setPluginUrl]=useState(''); const [plugins,setPlugins]=useState<string[]>([]); const [world,setWorld]=useState<any>({worldName:'world',seed:'',gamemode:'survival',difficulty:'normal',levelType:'minecraft:normal',reset:false}); const [files,setFiles]=useState<any[]>([]);
  const load=useCallback(async()=>{const r=await fetch('/api/servers/'+id);if(r.ok){const d=await r.json();setS(d);setSettings(d);setAliases(d.commandAliases||[]);const w=d.worlds?.[0];if(w)setWorld((v:any)=>({...v,worldName:w.name,seed:w.seed||'',gamemode:w.gamemode,difficulty:w.difficulty,levelType:w.levelType}))}},[id]);
  useEffect(()=>{load()},[load]);
  useEffect(()=>{if(tab!=='console'||!s)return;const refresh=async()=>{const r=await fetch('/api/servers/'+id+'/console');if(r.ok){const d=await r.json();setLogs(d.logs||'')}};refresh();const t=setInterval(refresh,2500);return()=>clearInterval(t)},[tab,id,s]);
  useEffect(()=>{if(tab==='plugins')fetch('/api/servers/'+id+'/plugins').then(r=>r.ok?r.json():{plugins:[]}).then(d=>setPlugins(d.plugins||[]));if(tab==='files')fetch('/api/servers/'+id+'/files').then(r=>r.ok?r.json():{files:[]}).then(d=>setFiles(d.files||[]))},[tab,id]);
  async function action(a:string){setBusy(true);setNotice('');const r=await fetch('/api/servers/'+id+'/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:a})});const d=await r.json();if(!r.ok)setNotice(d.error||'Aktion fehlgeschlagen');else{setNotice(a==='start'?'Server gestartet.':a==='stop'?'Server gestoppt.':'Server neu gestartet.');await load()}setBusy(false)}
  async function saveSettings(){setBusy(true);setNotice('');const body={...settings,ramMb:Number(settings.ramMb),maxPlayers:Number(settings.maxPlayers),commandAliases:aliases};const r=await fetch('/api/servers/'+id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)setNotice(d.error||'Speichern fehlgeschlagen');else{setS(d);setSettings(d);setNotice('Einstellungen gespeichert. Änderungen an Version/Type können einen Neustart benötigen.')}setBusy(false)}
  async function sendCommand(){if(!command.trim())return;const text=command;setCommand('');const r=await fetch('/api/servers/'+id+'/console',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:text})});const d=await r.json();setLogs(v=>v+`\n> ${text}\n${d.output||d.error||''}`)}
  async function saveWorld(reset:boolean){setBusy(true);const r=await fetch('/api/servers/'+id+'/world',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...world,reset})});const d=await r.json();setNotice(r.ok?(reset?'Welt zurückgesetzt und neu erstellt.':'Welteinstellungen gespeichert.'):d.error||'Weltfehler');await load();setBusy(false)}
  async function installPlugin(){if(!pluginUrl.trim())return;setBusy(true);const r=await fetch('/api/servers/'+id+'/plugins',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:pluginUrl.trim()})});const d=await r.json();setNotice(r.ok?`${d.file} installiert.`:d.error||'Plugin konnte nicht installiert werden');setPluginUrl('');const pr=await fetch('/api/servers/'+id+'/plugins');if(pr.ok)setPlugins((await pr.json()).plugins||[]);setBusy(false)}
  const address=useMemo(()=>s?.address||'',[s]);
  if(!s)return <main className="wrap"><Link className="btn dark" href="/dashboard">← Zurück</Link><p>Lade Server...</p></main>;
  return <main className="wrap">
    <div className="nav"><Link className="btn dark" href="/dashboard">← Server</Link><div className="logo">⛏ {s.name}</div><span className="pill">{s.status}</span></div>
    <div className="heroBox"><div className="muted">SERVER-ADRESSE</div><div style={{fontSize:28,fontWeight:800,marginTop:8}}>{address}</div><div className="muted" style={{marginTop:8}}>{s.motd}</div><div className="tabs"><button className="btn" disabled={busy} onClick={()=>action('start')}>▶ Start</button><button className="btn dark" disabled={busy} onClick={()=>action('stop')}>■ Stop</button><button className="btn dark" disabled={busy} onClick={()=>action('restart')}>↻ Restart</button>{notice&&<span className="muted" style={{alignSelf:'center'}}>{notice}</span>}</div></div>
    <div className="tabs"><button className="tab" onClick={()=>setTab('overview')}>Übersicht</button><button className="tab" onClick={()=>setTab('settings')}>⚙ Einstellungen</button><button className="tab" onClick={()=>setTab('world')}>🌍 Welt</button><button className="tab" onClick={()=>setTab('console')}>🖥 Konsole</button><button className="tab" onClick={()=>setTab('plugins')}>🧩 Plugins</button><button className="tab" onClick={()=>setTab('commands')}>⌘ Eigene Commands</button><button className="tab" onClick={()=>setTab('files')}>📁 Dateien</button><button className="tab" onClick={()=>setTab('players')}>👥 Spieler</button></div>
    {tab==='overview'&&<div className="grid"><div className="card"><h3>Software</h3><div className="stat">{s.type}</div><div className="muted">Minecraft {s.version}</div></div><div className="card"><h3>RAM</h3><div className="stat">{s.ramMb/1024} GB</div></div><div className="card"><h3>Spieler</h3><div className="stat">max. {s.maxPlayers}</div></div><div className="card"><h3>Spielmodus</h3><div className="stat" style={{fontSize:22}}>{s.gamemode}</div><div className="muted">Schwierigkeit: {s.difficulty}</div></div><div className="card"><h3>Hardcore</h3><div className="stat" style={{fontSize:22}}>{s.hardcore?'AKTIV':'Aus'}</div></div><div className="card"><h3>Port</h3><div className="stat" style={{fontSize:22}}>{s.port}</div></div></div>}
    {tab==='settings'&&<div className="card"><h2>Server-Einstellungen</h2><div className="grid" style={{gridTemplateColumns:'1fr 1fr'}}><input className="input" value={settings.name||''} onChange={e=>setSettings({...settings,name:e.target.value})} placeholder="Servername"/><input className="input" value={settings.motd||''} onChange={e=>setSettings({...settings,motd:e.target.value})} placeholder="MOTD"/><select className="input" value={settings.type||'PAPER'} onChange={e=>setSettings({...settings,type:e.target.value})}><option value="PAPER">Paper</option><option value="VANILLA">Vanilla</option><option value="SPIGOT">Spigot</option><option value="PURPUR">Purpur</option></select><select className="input" value={settings.version||'1.21.8'} onChange={e=>setSettings({...settings,version:e.target.value})}><option>1.21.8</option><option>1.21.7</option><option>1.21.6</option><option>1.21.5</option><option>1.20.6</option></select><select className="input" value={settings.ramMb||2048} onChange={e=>setSettings({...settings,ramMb:Number(e.target.value)})}><option value={1024}>1 GB</option><option value={2048}>2 GB</option><option value={4096}>4 GB</option><option value={8192}>8 GB</option></select><input className="input" type="number" min={1} max={100} value={settings.maxPlayers||20} onChange={e=>setSettings({...settings,maxPlayers:Number(e.target.value)})}/><select className="input" value={settings.gamemode||'survival'} onChange={e=>setSettings({...settings,gamemode:e.target.value})}><option>survival</option><option>creative</option><option>adventure</option><option>spectator</option></select><select className="input" value={settings.difficulty||'normal'} onChange={e=>setSettings({...settings,difficulty:e.target.value})}><option>peaceful</option><option>easy</option><option>normal</option><option>hard</option></select></div><div className="tabs"><label className="tab"><input type="checkbox" checked={!!settings.hardcore} onChange={e=>setSettings({...settings,hardcore:e.target.checked})}/> Hardcore</label><label className="tab"><input type="checkbox" checked={settings.pvp!==false} onChange={e=>setSettings({...settings,pvp:e.target.checked})}/> PvP</label><label className="tab"><input type="checkbox" checked={settings.onlineMode!==false} onChange={e=>setSettings({...settings,onlineMode:e.target.checked})}/> Online Mode</label><label className="tab"><input type="checkbox" checked={!!settings.whitelist} onChange={e=>setSettings({...settings,whitelist:e.target.checked})}/> Whitelist</label></div><button className="btn" disabled={busy} onClick={saveSettings}>Einstellungen speichern</button></div>}
    {tab==='world'&&<div className="card"><h2>Weltverwaltung</h2><div className="grid" style={{gridTemplateColumns:'1fr 1fr'}}><input className="input" value={world.worldName} onChange={e=>setWorld({...world,worldName:e.target.value})} placeholder="Weltname"/><input className="input" value={world.seed} onChange={e=>setWorld({...world,seed:e.target.value})} placeholder="Seed (leer = zufällig)"/><select className="input" value={world.gamemode} onChange={e=>setWorld({...world,gamemode:e.target.value})}><option>survival</option><option>creative</option><option>adventure</option></select><select className="input" value={world.difficulty} onChange={e=>setWorld({...world,difficulty:e.target.value})}><option>peaceful</option><option>easy</option><option>normal</option><option>hard</option></select><select className="input" value={world.levelType} onChange={e=>setWorld({...world,levelType:e.target.value})}><option value="minecraft:normal">Normal</option><option value="minecraft:flat">Flat</option><option value="minecraft:amplified">Amplified</option></select></div><div className="tabs"><button className="btn" disabled={busy} onClick={()=>saveWorld(false)}>Welt speichern</button><button className="btn dark" disabled={busy} onClick={()=>saveWorld(true)}>♻ Welt zurücksetzen</button></div><p className="muted">Beim Zurücksetzen wird der Weltordner gelöscht und beim nächsten Start mit den gewählten Einstellungen neu generiert.</p></div>}
    {tab==='console'&&<div className="card"><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>Live-Konsole</h2><span className="pill">automatisch aktualisiert</span></div><pre style={{background:'#050a06',padding:16,borderRadius:12,minHeight:360,maxHeight:520,overflow:'auto',whiteSpace:'pre-wrap'}}>{logs||'Noch keine Logausgabe.'}</pre><div style={{display:'flex',gap:8,marginTop:10}}><input className="input" value={command} onChange={e=>setCommand(e.target.value)} onKeyDown={e=>e.key==='Enter'&&sendCommand()} placeholder="Befehl, z. B. say Hallo"/><button className="btn" onClick={sendCommand}>Senden</button></div></div>}
    {tab==='plugins'&&<div className="card"><h2>Plugins</h2><p className="muted">Für Plugins muss der Servertyp Paper, Spigot oder Purpur sein. Füge eine direkte .jar-URL ein.</p><div style={{display:'flex',gap:8}}><input className="input" value={pluginUrl} onChange={e=>setPluginUrl(e.target.value)} placeholder="https://.../plugin.jar"/><button className="btn" disabled={busy||!pluginUrl.trim()} onClick={installPlugin}>Installieren</button></div><div className="grid" style={{marginTop:16}}>{plugins.length?plugins.map(x=><div className="card" key={x}>🧩 {x}</div>):<p className="muted">Noch keine Plugins installiert.</p>}</div></div>}
    {tab==='commands'&&<div className="card"><h2>Eigene Commands</h2><p className="muted">Erstelle einfache Bukkit/Paper-Command-Aliase. Beispiel: <b>/gm</b> → <b>gamemode</b>.</p>{aliases.map((a,i)=><div className="tabs" key={i}><input className="input" style={{flex:1}} value={a.alias} onChange={e=>setAliases(v=>v.map((x,j)=>j===i?{...x,alias:e.target.value}:x))}/><input className="input" style={{flex:2}} value={a.command} onChange={e=>setAliases(v=>v.map((x,j)=>j===i?{...x,command:e.target.value}:x))}/><button className="btn dark" onClick={()=>setAliases(v=>v.filter((_,j)=>j!==i))}>Löschen</button></div>)}<div className="tabs"><button className="btn dark" onClick={()=>setAliases(v=>[...v,{alias:'meincommand',command:'say Hallo'}])}>+ Command hinzufügen</button><button className="btn" disabled={busy} onClick={saveSettings}>Commands speichern</button></div></div>}
    {tab==='files'&&<div className="card"><h2>Dateien</h2><p className="muted">Serverdateien werden direkt im persistenten Serververzeichnis gespeichert.</p>{files.map(f=><div className="server card" style={{marginTop:8}} key={f.name}><span>{f.type==='directory'?'📁':'📄'} {f.name}</span><span className="muted">{f.size===null?'Ordner':`${Math.round(f.size/1024)} KB`}</span></div>)}</div>}
    {tab==='players'&&<div className="card"><h2>Spielerverwaltung</h2><p className="muted">Whitelist und OP-Verwaltung kannst du direkt über die Live-Konsole steuern, z. B. <code>whitelist add Spieler</code> oder <code>op Spieler</code>.</p></div>}
  </main>;
}