"use client";
import { useEffect, useState } from 'react';
import Link from 'next/link';

export default function ProviderPage(){
  const [state,setState]=useState<any>(null); const [busy,setBusy]=useState(false);
  const check=async()=>{setBusy(true);try{const r=await fetch('/api/hosting');setState(await r.json())}finally{setBusy(false)}};
  useEffect(()=>{check()},[]);
  return <main className="wrap"><div className="nav"><Link className="btn dark" href="/dashboard">← Dashboard</Link><div className="logo">🔌 Hosting</div></div><div className="card"><h1>Hosting verbinden</h1><p className="muted">StikeHost kann echte Minecraft-Server über einen externen Hosting-Provider verwalten. Die Verbindung läuft serverseitig; API-Schlüssel gehören nicht in den Browser oder ins GitHub-Repository.</p><div className="card" style={{marginTop:16}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>Falix</h2><span className="pill">{state?.configured?'Verbunden':'Nicht verbunden'}</span></div>{state?.account&&<div className="muted" style={{marginTop:6}}>Konto: {state.account}</div>}<div className="tabs"><a className="btn" href="https://client.falixnodes.net/profile/apikeys" target="_blank" rel="noreferrer">Falix API Keys öffnen</a><button className="btn dark" disabled={busy} onClick={check}>{busy?'Prüfe...':'↻ Verbindung prüfen'}</button></div>{!state?.configured&&<div className="card" style={{marginTop:12}}><b>Noch nicht verbunden</b><p className="muted">Der Betreiber der StikeHost-Instanz muss den Falix-API-Key als geheime Umgebungsvariable <code>FALIX_API_KEY</code> setzen. Danach kann StikeHost echte Server-APIs von Falix verwenden.</p></div>}</div><div className="grid" style={{marginTop:18}}><Link className="card tab" href="/dashboard">🖥 Server verwalten</Link><Link className="card tab" href="/dashboard">⌘ Konsole öffnen</Link><Link className="card tab" href="/dashboard">📁 Dateien & Backups</Link></div></div></main>;
}