const express = require('express');
const { execFile } = require('child_process');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const https = require('https');
const http = require('http');

const app = express();
app.use(express.json({ limit: '2mb' }));
const SECRET = process.env.WORKER_SECRET || 'dev';
const ROOT = '/srv/stikehost';
const DEFAULT_IMAGE = 'itzg/minecraft-server:latest';
fs.mkdirSync(ROOT, { recursive: true });
function auth(req,res,next){if(req.get('X-Worker-Secret')!==SECRET)return res.status(401).json({error:'unauthorized'});next()}
function run(args,options={}){return new Promise((resolve,reject)=>execFile('docker',args,{timeout:60000,maxBuffer:4*1024*1024,...options},(e,so,se)=>e?reject(new Error((se||so||e.message).trim())):resolve((so||'').trim())))}
function shell(args,options={}){return new Promise((resolve,reject)=>execFile(args[0],args.slice(1),{timeout:120000,maxBuffer:4*1024*1024,...options},(e,so,se)=>e?reject(new Error((se||so||e.message).trim())):resolve((so||'').trim())))}
function dirFor(id){if(!/^[a-zA-Z0-9_-]+$/.test(id))throw new Error('invalid server id');const dir=path.join(ROOT,id);fs.mkdirSync(dir,{recursive:true});return dir}
function containerName(id){return `stikehost_${id}`}
function bool(v,f=false){return v===undefined?f:Boolean(v)}
function envMap(info){const m={};for(const x of info?.Config?.Env||[]){const i=x.indexOf('=');if(i>0)m[x.slice(0,i)]=x.slice(i+1)}return m}
function cleanPart(v,f='file'){const x=String(v||f).replace(/[^a-zA-Z0-9._-]/g,'_');if(x==='.'||x==='..')throw new Error('invalid path');return x.slice(0,160)}
function propertiesFromConfig(c){const lines=[`motd=${String(c.motd??'A Minecraft Server').replace(/\r?\n/g,' ')}`,`max-players=${Number(c.maxPlayers??20)}`,`gamemode=${c.gamemode??'survival'}`,`difficulty=${c.difficulty??'normal'}`,`hardcore=${bool(c.hardcore)}`,`pvp=${bool(c.pvp,true)}`,`online-mode=${bool(c.onlineMode,true)}`,`white-list=${bool(c.whitelist)}`,'enable-command-block=true','enable-rcon=true'];if(c.worldName)lines.push(`level-name=${String(c.worldName).replace(/[^a-zA-Z0-9_-]/g,'_')}`);if(c.seed!==undefined&&c.seed!==null)lines.push(`level-seed=${String(c.seed)}`);if(c.levelType)lines.push(`level-type=${String(c.levelType)}`);return lines.join('\n')+'\n'}
function writeProperties(id,c){const file=path.join(dirFor(id),'server.properties');const current=fs.existsSync(file)?fs.readFileSync(file,'utf8'):'';const map=new Map();for(const line of current.split(/\r?\n/)){const i=line.indexOf('=');if(i>0&&!line.startsWith('#'))map.set(line.slice(0,i),line.slice(i+1))}for(const line of propertiesFromConfig(c).trim().split('\n')){const i=line.indexOf('=');if(i>0)map.set(line.slice(0,i),line.slice(i+1))}fs.writeFileSync(file,[...map.entries()].map(([k,v])=>`${k}=${v}`).join('\n')+'\n')}
function writeAliases(id,a){const clean=(Array.isArray(a)?a:[]).filter(x=>x&&/^[a-zA-Z0-9_-]+$/.test(String(x.alias))&&String(x.command||'').trim());const body=clean.length?`aliases:\n${clean.map(x=>`  ${x.alias}:\n    - "${String(x.command).replace(/"/g,'\\"')}"`).join('\n')}\n`:'aliases: {}\n';fs.writeFileSync(path.join(dirFor(id),'commands.yml'),body)}
async function inspect(id){try{return JSON.parse(await run(['inspect',containerName(id),'--format','{{json .}}']))}catch{return null}}
async function createContainer(id,c){const name=containerName(id),dir=dirFor(id);const rcon=crypto.createHash('sha256').update(`${SECRET}:${id}`).digest('hex').slice(0,32);const memory=Math.max(1024,Number(c.ramMb||2048));const env=[`EULA=TRUE`,`VERSION=${c.version||'1.21.8'}`,`TYPE=${c.type||'VANILLA'}`,`MEMORY=${memory}M`,`RCON_PASSWORD=${rcon}`,'ENABLE_RCON=true',`MOTD=${c.motd||'A Minecraft Server'}`,`MAX_PLAYERS=${Number(c.maxPlayers||20)}`,`MODE=${c.gamemode||'survival'}`,`DIFFICULTY=${c.difficulty||'normal'}`,`HARDCORE=${bool(c.hardcore)}`,`PVP=${bool(c.pvp,true)}`,`ONLINE_MODE=${bool(c.onlineMode,true)}`,`ENABLE_WHITELIST=${bool(c.whitelist)}`,'ENABLE_COMMAND_BLOCK=true'];await run(['create','--name',name,'--restart','unless-stopped','--memory',`${memory}m`,'-p',`${Number(c.port)}:25565/tcp`,'-v',`${dir}:/data`,...env.flatMap(v=>['-e',v]),DEFAULT_IMAGE]);writeProperties(id,c);writeAliases(id,c.commandAliases);return name}
async function ensure(id,c){return(await inspect(id))?containerName(id):createContainer(id,c)}
async function state(id){const info=await inspect(id);if(!info)return{status:'missing'};return{status:info.State?.Running?'running':(info.State?.Status||'stopped'),container:info.Name?.replace(/^\//,'')||containerName(id),startedAt:info.State?.StartedAt||null,exitCode:info.State?.ExitCode??0,image:info.Config?.Image||DEFAULT_IMAGE}}
async function publicIp(){return new Promise((resolve,reject)=>{const req=https.get('https://api.ipify.org',{timeout:5000},r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>r.statusCode===200?resolve(d.trim()):reject(new Error(`IP lookup failed: ${r.statusCode}`)))});req.on('timeout',()=>{req.destroy();reject(new Error('IP lookup timeout'))});req.on('error',reject)})}
function fetchUrl(url,dest){return new Promise((resolve,reject)=>{const lib=url.startsWith('https:')?https:http;const req=lib.get(url,{headers:{'User-Agent':'StikeHost/1.0'},timeout:15000},res=>{if([301,302,307,308].includes(res.statusCode)&&res.headers.location){res.resume();return fetchUrl(res.headers.location,dest).then(resolve,reject)}if(res.statusCode!==200){res.resume();return reject(new Error(`Download failed: ${res.statusCode}`))}const out=fs.createWriteStream(dest);res.pipe(out);out.on('finish',()=>out.close(resolve));out.on('error',reject)});req.on('timeout',()=>{req.destroy(new Error('download timeout'))});req.on('error',reject)})}
app.get('/health',(_,res)=>res.json({ok:true}));app.use('/v1',auth);
app.get('/v1/public-ip',async(_,res)=>{try{res.json({ip:await publicIp()})}catch(e){res.status(502).json({error:e.message})}});
app.get('/v1/servers/:id/status',async(req,res)=>{try{res.json(await state(req.params.id))}catch(e){res.status(500).json({error:e.message})}});
app.get('/v1/servers/:id/logs',async(req,res)=>{try{const n=Math.min(1000,Math.max(20,Number(req.query.lines||250)));res.json({logs:await run(['logs','--tail',String(n),containerName(req.params.id)])})}catch(e){res.json({logs:`No logs yet: ${e.message}`})}});
app.post('/v1/servers/:id/start',async(req,res)=>{try{await ensure(req.params.id,req.body||{});await run(['start',containerName(req.params.id)]);res.json(await state(req.params.id))}catch(e){res.status(500).json({error:e.message})}});
app.post('/v1/servers/:id/stop',async(req,res)=>{try{await run(['stop','-t','20',containerName(req.params.id)]);res.json(await state(req.params.id))}catch(e){res.status(500).json({error:e.message})}});
app.post('/v1/servers/:id/restart',async(req,res)=>{try{await run(['restart','-t','20',containerName(req.params.id)]);res.json(await state(req.params.id))}catch(e){res.status(500).json({error:e.message})}});
app.post('/v1/servers/:id/command',async(req,res)=>{try{const command=String(req.body?.command||'').trim();if(!command||command.length>500||/[\r\n]/.test(command))return res.status(400).json({error:'Invalid command'});if(!(await inspect(req.params.id))?.State?.Running)return res.status(409).json({error:'Server is not running'});res.json({output:await run(['exec',containerName(req.params.id),'rcon-cli',...command.split(/\s+/)])})}catch(e){res.status(500).json({error:e.message})}});
app.post('/v1/servers/:id/config',async(req,res)=>{try{const c=req.body||{};let info=await inspect(req.params.id);const wasRunning=Boolean(info?.State?.Running);const env=envMap(info||{});const recreate=info&&((c.version&&env.VERSION&&c.version!==env.VERSION)||(c.type&&env.TYPE&&c.type!==env.TYPE));if(recreate){await run(['rm','-f',containerName(req.params.id)]);info=null}const name=info?containerName(req.params.id):await createContainer(req.params.id,c);writeProperties(req.params.id,c);writeAliases(req.params.id,c.commandAliases);if(c.ramMb)await run(['update','--memory',`${Math.max(1024,Number(c.ramMb))}m`,name]);if(wasRunning||recreate){await run(['start',name]);if(wasRunning&&!recreate)await run(['restart','-t','20',name])}res.json(await state(req.params.id))}catch(e){res.status(500).json({error:e.message})}});
app.post('/v1/servers/:id/plugins/install',async(req,res)=>{try{const url=String(req.body?.url||'').trim();if(!/^https?:\/\//i.test(url))return res.status(400).json({error:'Plugin URL must be http(s)'});const dir=path.join(dirFor(req.params.id),'plugins');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,(String(req.body?.fileName||`plugin-${Date.now()}.jar`).replace(/[^a-zA-Z0-9._-]/g,'_').replace(/\.jar$/i,'')+'.jar'));await fetchUrl(url,file);res.json({ok:true,file:path.basename(file)})}catch(e){res.status(500).json({error:e.message})}});
app.get('/v1/servers/:id/plugins',async(req,res)=>{try{const dir=path.join(dirFor(req.params.id),'plugins');fs.mkdirSync(dir,{recursive:true});res.json({plugins:fs.readdirSync(dir).filter(x=>x.toLowerCase().endsWith('.jar')).sort()})}catch(e){res.status(500).json({error:e.message})}});
app.post('/v1/servers/:id/world/reset',async(req,res)=>{try{const world=cleanPart(req.body?.world,'world');const dir=dirFor(req.params.id);const info=await inspect(req.params.id);const running=Boolean(info?.State?.Running);if(running)await run(['stop','-t','20',containerName(req.params.id)]);fs.rmSync(path.join(dir,world),{recursive:true,force:true});writeProperties(req.params.id,{worldName:world,seed:req.body?.seed,levelType:req.body?.levelType});await run(['start',containerName(req.params.id)]);res.json({ok:true,world})}catch(e){res.status(500).json({error:e.message})}});
app.get('/v1/servers/:id/files',async(req,res)=>{try{const dir=dirFor(req.params.id);res.json({files:fs.readdirSync(dir,{withFileTypes:true}).map(x=>({name:x.name,type:x.isDirectory()?'directory':'file',size:x.isFile()?fs.statSync(path.join(dir,x.name)).size:null}))})}catch(e){res.status(500).json({error:e.message})}});
app.get('/v1/servers/:id/file',async(req,res)=>{try{const name=cleanPart(req.query.name);const file=path.join(dirFor(req.params.id),name);if(!fs.existsSync(file)||!fs.statSync(file).isFile())return res.status(404).json({error:'File not found'});if(fs.statSync(file).size>1024*1024)return res.status(413).json({error:'File too large'});res.json({name,content:fs.readFileSync(file,'utf8')})}catch(e){res.status(400).json({error:e.message})}});
app.post('/v1/servers/:id/file',async(req,res)=>{try{const name=cleanPart(req.body?.name);const content=String(req.body?.content||'');if(content.length>1024*1024)return res.status(413).json({error:'File too large'});fs.writeFileSync(path.join(dirFor(req.params.id),name),content);res.json({ok:true,name})}catch(e){res.status(400).json({error:e.message})}});
app.post('/v1/servers/:id/backup',async(req,res)=>{try{const dir=dirFor(req.params.id);const backups=path.join(ROOT,'backups',req.params.id);fs.mkdirSync(backups,{recursive:true});const name=cleanPart(req.body?.name,`backup-${new Date().toISOString().replace(/[:.]/g,'-')}`)+'.tar.gz';const target=path.join(backups,name);await shell(['tar','-czf',target,'-C',dir,'.']);res.json({ok:true,name,size:fs.statSync(target).size})}catch(e){res.status(500).json({error:e.message})}});
app.get('/v1/servers/:id/backups',async(req,res)=>{try{const dir=path.join(ROOT,'backups',req.params.id);fs.mkdirSync(dir,{recursive:true});res.json({backups:fs.readdirSync(dir).filter(x=>x.endsWith('.tar.gz')).map(name=>({name,size:fs.statSync(path.join(dir,name)).size,createdAt:fs.statSync(path.join(dir,name)).mtime.toISOString()})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))})}catch(e){res.status(500).json({error:e.message})}});
app.listen(4000,()=>console.log('StikeHost worker listening on 4000'));
