"use client";
import { useEffect, useState } from 'react';
import Link from 'next/link';

type Server = { id:string; name:string; slug:string; version:string; type:string; status:string; ramMb:number; port:number; address?:string; provider?:string; };

const initialForm={name:'',version:'1.21.8',type:'PAPER',ramMb:2048,motd:'A Minecraft Server',maxPlayers:20,gamemode:'survival',difficulty:'normal',hardcore:false,pvp:true,onlineMode:true,whitelist:false,seed:''};

export default function Dashboard(){
  const [servers,setServers]=useState<Server[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [provider,setProvider]=useState<any>(null); const [form,setForm]=useState(initialForm);
  const load=()=>fetch('/api/servers').then(r=>r.ok?r.json():[]).then(setServers);
  useEffect(()=>{load();fetch('/api/hosting').then(r=>r.json()).then(setProvider).catch(()=>setProvider({configured:false}))},[]);
  function set<K extends keyof typeof form>(key:K,value:(typeof form)[K]){setForm(v=>({...v,[key]:value}));}
  async function create(){setBusy(true);setMessage('');const r=await fetch('/api/servers',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();if(!r.ok)setMessage(d.error||'Fehler');else{setMessage('Server erstellt. Öffne ihn unten und drücke Start.');setForm(initialForm);await load()}setBusy(false)}
  async function quick(id:string,action:string){const r=await fetch(`/api/servers/${id}/action`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})});if(!r.ok){const d=await r.json();setMessage(d.error||'Aktion fehlgeschlagen')}else await load()}
  return <main className="wrap">
    <div className="nav"><div className="logo">⛏ StikeHost</div><div className="tabs" style={{margin:0}}><Link className="btn dark" href="/">Startseite</Link><button className="btn dark" onClick={load}>↻ Aktualisieren</button></div></div>
    <div className="dash"><aside className="side"><div className="card"><h3>Server Panel</h3><div className="tabs" style={{flexDirection:'column'}}><button className="tab" onClick={()=>document.getElementById('create')?.scrollIntoView({behavior:'smooth'})}>➕ Server erstellen</button><button className="tab" onClick={()=>document.getElementById('servers')?.scrollIntoView({behavior:'smooth'})}>🖥 Meine Server</button><Link className="tab" href="/dashboard/provider">🔌 Hosting verbinden</Link></div></div><div className="card" style={{marginTop:12}}><div className="muted">Hosting</div><div style={{fontWeight:800,marginTop:6}}>{provider?.configured?'🟢 Falix verbunden':'🟡 Eigener Docker-Host'}</div>{provider?.account&&<div className="muted" style={{marginTop:4}}>{provider.account}</div>}<Link className="btn dark" style={{marginTop:12}} href="/dashboard/provider">Verwalten</Link></div></aside>
    <section>
      <div id="create" className="card"><h1>Neuen Server erstellen</h1><p className="muted">Alle Felder sind echte Server-Einstellungen. Nach dem Erstellen kannst du im Server-Panel Konsole, Welt, Plugins, Dateien, Spieler und Backups bedienen.</p>
        <div className="grid" style={{gridTemplateColumns:'1fr 1fr'}}>
          <input className="input" placeholder="Servername" value={form.name} onChange={e=>set('name',e.target.value)}/><select className="input" value={form.version} onChange={e=>set('version',e.target.value)}><option>1.21.8</option><option>1.21.7</option><option>1.21.6</option><option>1.21.5</option><option>1.20.6</option></select>
          <select className="input" value={form.type} onChange={e=>set('type',e.target.value)}><option value="PAPER">Paper</option><option value="VANILLA">Vanilla</option><option value="SPIGOT">Spigot</option><option value="PURPUR">Purpur</option></select><select className="input" value={form.ramMb} onChange={e=>set('ramMb',Number(e.target.value))}><option value={1024}>1 GB RAM</option><option value={2048}>2 GB RAM</option><option value={4096}>4 GB RAM</option><option value={8192}>8 GB RAM</option></select>
          <input className="input" placeholder="MOTD" value={form.motd} onChange={e=>set('motd',e.target.value)}/><input className="input" type="number" min={1} max={100} placeholder="Max. Spieler" value={form.maxPlayers} onChange={e=>set('maxPlayers',Number(e.target.value))}/>
          <select className="input" value={form.gamemode} onChange={e=>set('gamemode',e.target.value)}><option value="survival">Survival</option><option value="creative">Creative</option><option value="adventure">Adventure</option><option value="spectator">Spectator</option></select><select className="input" value={form.difficulty} onChange={e=>set('difficulty',e.target.value)}><option value="peaceful">Peaceful</option><option value="easy">Easy</option><option value="normal">Normal</option><option value="hard">Hard</option></select>
          <input className="input" placeholder="Seed (leer = zufällig)" value={form.seed} onChange={e=>set('seed',e.target.value)}/>
        </div>
        <div className="tabs"><label className="tab"><input type="checkbox" checked={form.hardcore} onChange={e=>set('hardcore',e.target.checked)}/> Hardcore</label><label className="tab"><input type="checkbox" checked={form.pvp} onChange={e=>set('pvp',e.target.checked)}/> PvP</label><label className="tab"><input type="checkbox" checked={form.onlineMode} onChange={e=>set('onlineMode',e.target.checked)}/> Online Mode</label><label className="tab"><input type="checkbox" checked={form.whitelist} onChange={e=>set('whitelist',e.target.checked)}/> Whitelist</label></div>
        <button className="btn" disabled={busy||!form.name.trim()} onClick={create}>{busy?'Server wird erstellt...':'⚡ Server erstellen'}</button>{message&&<div className="muted" style={{marginTop:12}}>{message}</div>}
      </div>
      <div id="servers" className="card" style={{marginTop:18}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><h2>Meine Server</h2><span className="pill">{servers.length} Server</span></div>{servers.length===0?<p className="muted">Noch kein Server. Erstelle oben deinen ersten.</p>:servers.map(s=><div className="card server" key={s.id} style={{marginTop:10}}><Link href={'/dashboard/server/'+s.id}><div><div style={{fontSize:20,fontWeight:800}}>{s.name}</div><div className="muted">{s.type} · {s.version} · {s.ramMb/1024} GB · {s.provider||'local'}</div></div></Link><div className="tabs" style={{margin:0}}><span className="pill">{s.status}</span><button className="btn dark" onClick={()=>quick(s.id,s.status==='running'?'stop':'start')}>{s.status==='running'?'■ Stop':'▶ Start'}</button><Link className="btn" href={'/dashboard/server/'+s.id}>Öffnen</Link></div></div>)}</div>
    </section></div></main>;
}